---
title: "Lab10"
author: "Narciso"
date: "11/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
###Part I - Reading VCF data
```{r}
library(vcfR)

data(vcfR_example)
vcf

strwrap(vcf@meta[1:7])

queryMETA(vcf)

queryMETA(vcf, element = 'DP')

queryMETA(vcf, element = 'FORMAT=<ID=DP')

head(getFIX(vcf))

vcf@gt[1:6, 1:4]

vcf <- read.vcfR("Data/pinfsc50_filtered.vcf.gz")

head(vcf)

write.vcf(vcf, "myVCFdata_filtered.vcf.gz")

```
Exercises Part 1
```{r}
#1
?read.vcfR
#2
queryMETA(vcf, element = 'AD')
#3
tail(vcf@fix)
#4
plot(vcf)

# Alternate ggplot2 answer.
library(ggplot2)
qplot(getQUAL(vcf), geom = "histogram")
#5
colnames(vcf@gt)
```

###Part II - Analysis of Genome Data
```{r, eval=TRUE}

library('vcfR')

vcf <- read.vcfR("Data/pinfsc50_filtered.vcf.gz")

vcf

x <- vcfR2genlight(vcf)

x

# vcfR
gt <- extract.gt(vcf, element = "GT")
gt[c(2,6,18), 1:3]

# genlight
t(as.matrix(x))[c(1,5,17), 1:3]

library(adegenet)
pop(x) <- as.factor(c("us", "eu", "us", "af", "eu", "us", "mx", "eu", "eu", "sa", "mx", "sa", "us", "sa", "Pmir", "us", "eu", "eu"))
popNames(x)

ploidy(x) <- 2

x.dist <- dist(x)

x.dist <- poppr::bitwise.dist(x)

library(vcfR)

# Find the files.
vcf_file <- system.file("extdata", "pinf_sc50.vcf.gz", package = "pinfsc50")
dna_file <- system.file("extdata", "pinf_sc50.fasta", package = "pinfsc50")
gff_file <- system.file("extdata", "pinf_sc50.gff", package = "pinfsc50")

# Input the files.
vcf <- read.vcfR(vcf_file, verbose = FALSE)
dna <- ape::read.dna(dna_file, format = "fasta")
gff <- read.table(gff_file, sep="\t", quote="")

# Create a chromR object.
chrom <- create.chromR(name="Supercontig", vcf=vcf, seq=dna, ann=gff, verbose=TRUE)

chrom

plot(chrom)

chromoqc(chrom, dp.alpha = 66)

chrom <- proc.chromR(chrom, verbose = TRUE)

plot(chrom)

chromoqc(chrom, dp.alpha = 66)

#vcf <- read.vcfR("pinfsc50_qc.vcf.gz", verbose = FALSE)
vcf <- read.vcfR("pinfsc50_filtered.vcf.gz", verbose = FALSE)
chrom <- create.chromR(name="Supercontig", vcf=vcf, seq=dna, ann=gff, verbose=FALSE)
chrom <- proc.chromR(chrom, verbose = FALSE)
chromoqc(chrom, dp.alpha = 66)

head(chrom@var.info)

head(chrom@win.info)

library(vcfR)
data(vcfR_example)
pop <- as.factor(c("us", "eu", "us", "af", "eu", "us", "mx", "eu", "eu", "sa", "mx", "sa", "us", "sa", "Pmir", "us", "eu", "eu"))
myDiff <- genetic_diff(vcf, pops = pop, method = 'nei')
knitr::kable(head(myDiff[,1:15]))

knitr::kable(head(myDiff[,16:19]))

knitr::kable(round(colMeans(myDiff[,c(3:9,16,19)], na.rm = TRUE), digits = 3))

library(reshape2)
library(ggplot2)

dpf <- melt(myDiff[,c(3:8,19)], varnames=c('Index', 'Sample'), value.name = 'Depth', na.rm=TRUE)

p <- ggplot(dpf, aes(x=variable, y=Depth)) + geom_violin(fill="#2ca25f", adjust = 1.2)
p <- p + xlab("")
p <- p + ylab("")
p <- p + theme_bw()
p

```
###Exercises Part 2
```{r, eval=TRUE}
data(vcfR_example)
pop <- as.factor(c("us", "eu", "us", "af", "eu", "us", "mx", "eu", "eu", "sa", "mx", "sa", "us", "sa", "Pmir", "us", "eu", "eu"))
myDiff <- genetic_diff(vcf, pops = pop, method = 'nei')
knitr::kable(head(myDiff[,1:15]))

knitr::kable(head(myDiff[,16:19]))

knitr::kable(round(colMeans(myDiff[,c(3:9,16,19)], na.rm = TRUE), digits = 3))

library(reshape2)
library(ggplot2)

dpf <- melt(myDiff[,c(3:8,19)], varnames=c('Index', 'Sample'), value.name = 'Depth', na.rm=TRUE)

p <- ggplot(dpf, aes(x=variable, y=Depth)) + geom_violin(fill="#2ca25f", adjust = 1.2)
p <- p + xlab("")
p <- p + ylab("")
p <- p + theme_bw()
p
#1
plot(getPOS(vcf), myDiff$Gprimest,  pch = 20, col = "#1E90FF44", xlab = "", ylab = "", ylim = c(0, 1), xaxt = "n")
axis(side = 1, at = seq(0, 1e5, by = 1e4), labels = seq(0, 100, by = 10))
title(xlab='Genomic position (Kbp)')
title(ylab = expression(italic("G'"["ST"])))

#2
table(pop)
#small sample size
#3

chromoqc(chrom, dp.alpha = 66, xlim = c(2e05, 4e05))
#4
queryMETA(vcf)

```

