---
title: "lab9x"
author: "Narciso"
date: "10/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}


## Generate a uniform random number
x <- runif(5, 0, 20)  
if(x > 6) {
        y <- 20
} else {
        y <- 0
}

for(i in 1:20) {
        print(i)
}

x <- c("e", "f", "g", "h")
for(i in 1:4) {
        ## Print out each element of 'x'
        print(x[i])  
}

## Generate a sequence based on length of 'x'
for(i in seq_along(x)) {   
        print(x[i])
}

for(letter in x) {
        print(letter)
}

for(i in 1:4) print(x[i])

x <- matrix(1:6, 2, 3)
for(i in seq_len(nrow(x))) {
        for(j in seq_len(ncol(x))) {
                print(x[i, j])
        }   
}

count <- 0
while(count < 10) {
        print(count)
        count <- count + 1
}

z <- 5
set.seed(1)
while(z >= 3 && z <= 10) {
        coin <- rbinom(1, 1, 0.5)
        
        if(coin == 1) {  ## random walk
                z <- z + 1
        } else {
                z <- z - 1
        } 
}
print(z)

f <- function() {
        ## This is an empty function
}
## Functions have their own class
class(f) 

## Execute this function
f()       

f <- function() {
        cat("Hello, world!\n")
}
f()

f <- function(num) {
        for(i in seq_len(num)) {
                cat("Hello, world!\n")
        }
}
f(3)

f <- function(num) {
        hello <- "Hello, world!\n"
        for(i in seq_len(num)) {
                cat(hello)
        }
        chars <- nchar(hello) * num
        chars
}
meaningoflife <- f(3)

print(meaningoflife)

f <- function(num = 1) {
        hello <- "Hello, world!\n"
        for(i in seq_len(num)) {
                cat(hello)
        }
        chars <- nchar(hello) * num
        chars
}
f()    ## Use default value for 'num'

f(2)   ## Use user-specified value

f(num = 2)


```

